### ISSUE TITLE
Short-circuiting of partitioner behavior when using a string or {_id: string}

### ISSUE THREAD

**Issue by damienrobson** [mizzao/meteor-partitioner#9]
We have an issue where publishing a route with specific selectors seems to be ignoring the Partitioner's find hook (potentially around _italic_ selector._groupId = groupId, line 159 of grouping.coffee_italic_ ). By publishing a collection that takes a single parameter of an entity's ID value, we can retrieve and interact with entities that are not within the scope of the current user's group. 

The following returns as expected (correct groups):
Meteor.publish("allItems", function() {
  return items.find({});
});

The following brings back items we shouldn't be seeing:
Meteor.publish("itemsById", function(itemId) {
  return items.find({
    _id: itemId
  });
});

**Comment by mizzao** [comment]
Sorry for the delayed response as I was on vacation.

As for this issue - it was by design originally, and I didn't fully explain it in the documentation. Selectors with a single `_id` either in the form of a string or `{_id: "..."}` are commonly used and I decided to deliberately omit rewriting them for performance reasons. Both types of selectors would be written as

```
{
  _id: "...",
  _groupId: "..."
}
```

The idea is that if you don't know the `_id`, you shouldn't be able to retrieve the document. But I understand that this might cause unforeseen security issues, so it would be good to understand your use case better.

Partitioner is designed more for lightweight segmentation within a particular app rather than as a secure container solution, so we should consider if performance might be an issue. This might be a non-issue if we get meteor/meteor#395 implemented.

**Comment by Skulmuk** [comment]
Not a problem, thanks for getting back to me on this. We've managed to sort it out.

**Comment by mizzao** [comment]
Hey @Skulmuk - @jamiecollinson also described this as a potentially important issue to resolve in #10. Would you mind telling me a bit more about how exactly you've sorted it out, and if making the change for `_id` selects to also filter by group would work for you?

**Comment by Skulmuk** [comment]
The way Jamie has done it works for us quite well (we're working on the same project) - see his pull request :)

**Comment by mizzao** [comment]
Re-opening as this may trip people up when using partitioner.

I haven't seen a compelling reason to remove this yet, but good to have it out there in case someone wonders.

**Comment by mizzao** [comment]
v0.5.7 fixes #4 and #13, but doesn't short-circuit for ObjectIDs (in the rare cases where those are used). We can fix that if anyone raises an issue.
